import { InjectionToken } from '@angular/core';

declare global {
  interface Window {
    __APP_CONFIG__?: {
      supabaseUrl?: string;
      supabaseAnonKey?: string;
    };
  }
}

export interface AppConfig {
  supabaseUrl: string;
  supabaseAnonKey: string;
}

/**
 * Runtime application configuration via InjectionToken.
 *
 * Values are read from window.__APP_CONFIG__ (generated by scripts/generate-app-config.mjs).
 * This follows Angular's recommended DI pattern for non-class dependencies.
 *
 * @see https://angular.dev/guide/di/defining-dependency-providers#injectiontoken-with-providedin-root
 */
export const APP_CONFIG = new InjectionToken<AppConfig>('app.config', {
  providedIn: 'root',
  factory: () => {
    const runtimeConfig = window.__APP_CONFIG__ ?? {};
    return {
      supabaseUrl: runtimeConfig.supabaseUrl ?? '',
      supabaseAnonKey: runtimeConfig.supabaseAnonKey ?? '',
    };
  },
});
